### ISSUE TITLE
Please consider make crate description more informative

### ISSUE THREAD

**Issue by nospam3089** [Geal/rust-syslog#67]
Currently the description for this crate reads (in full):

> Send log messages to syslog

How about updating it to something along the lines of:

> Pure Rust implementation for sending log messages to syslog on platforms supporting ipc, tcp or udp sockets

?

That way how the crate actually works would become more obvious for users of the crate.

At least my expectation was that a crate under this name would work on any system providing the relevant Posix API, not relying on specific implementation details.

**Comment by Geal** [comment]
fixed in https://github.com/Geal/rust-syslog/commit/4f8b5d0f2845bb199651d8a6fa0ad3f852662be5

**Comment by nospam2624** [comment]
That's better, but arguably not really a full fix of the issue as filed. The new phrasing still leaves out crucial information which potential consumers of the crate desire to know.

> Syslog message formatter and writer, supporting unix sockets, UDP and TCP exporters

The above sentence has no mention on **how** the crate works. I held a presentation on the state of the Rust syslog crate landscape which you ought to find interesting. Unfortunately the presentation wasn't recorded, but you might wish to have a quick look at the slide deck published at https://blog.netizen.se/p/rust-crate-libsyslog/ and see if it gives you anything.

Please scroll through the linked slide-deck and then reconsider whether you could mention that this is a pure Rust rewrite. Objective, correct and complete descriptions are things to strive for, right?

Thanks for your work! I respectfully appreciate the effort, even if this crate turned out to be impossible for me to use due to the bugs described in the slide-deck.
